
[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }
size = 9.5
builtin_box_drawing = true

[window]
opacity = 0.95

[general]
import = ["~/.config/alacritty-theme/themes/challenger_deep.toml"]

[colors.cursor]
cursor = "#ccff00"
text = "#000000"

[cursor]
blink_interval = 250

[cursor.style]
blinking = "always"
