font:
  normal:
    family: JetBrains Mono
    style: Regular
  size: %%font_size%%
  builtin_box_drawing: true

colors:
  primary:
    background: '0x1F2430'
    foreground: '0xDDDDDD'
  normal:
    black:   '0x1F2430'
    red:     '0xFF3333'
    green:   '0xA6CC70'
    yellow:  '0xFFD580'
    blue:    '0x77A8D9'
    magenta: '0xB48EAD'
    cyan:    '0x95E6CB'
    white:   '0xCBCCC6'
  bright:
    black:   '0xBFBAB0'
    red:     '0xFF3333'
    green:   '0xBAE67E'
    yellow:  '0xFFE6B3'
    blue:    '0x73D0FF'
    magenta: '0xD4BFFF'
    cyan:    '0x5CCFE6'
    white:   '0xFFFFFF'
  cursor:
    text: '#000000'
    cursor: '#a6e22d'
