font:
  normal:
    family: JetBrains Mono
    style: Regular
  size: %%font_size%%
  builtin_box_drawing: true

import:
  - ~/.config/alacritty-theme/themes/argonaut.yaml

colors:
  primary:
    foreground: '#dddddd'
  normal:
    black: '#555555'
  cursor:
    text: '#000000'
    cursor: '#a6e22d'

window:
  opacity: 0.91
