window:
  dimensions:
    columns: 160
    lines: 50

font:
  normal:
    family: JetBrains Mono
  size: 11

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 1
    y: 2
  use_thin_strokes: true

# If `true`, bold text is drawn using the bright color variants.
#draw_bold_text_with_bright_colors: false

# Terminal.sexy
colors:
  # Default colors
  primary:
    background: '0x1F2430'
    #foreground: '0xCBCCC6'
    foreground: '0xDDDDDD'

  # Normal colors
  normal:
    black:   '0x1F2430'
    red:     '0xFF3333'
    green:   '0xA6CC70'
    yellow:  '0xFFD580'
    blue:    '0x77A8D9'
    magenta: '0xB48EAD'
    cyan:    '0x95E6CB'
    white:   '0xCBCCC6'

  # Bright colors
  bright:
    black:   '0xBFBAB0'
    red:     '0xFF3333'
    green:   '0xBAE67E'
    yellow:  '0xFFE6B3'
    blue:    '0x73D0FF'
    magenta: '0xD4BFFF'
    cyan:    '0x5CCFE6'
    white:   '0xFFFFFF'

  cursor:
    text: '#000000'
    cursor: '#a6e22d'
