
[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono" }
size = 9.5
builtin_box_drawing = true

[window]
opacity = 0.95

[general]
import = [
    "~/.config/alacritty-theme/themes/argonaut.toml"
]
