#!/bin/sh

export TERMINAL=alacritty
export GDK_SCALE=1
export GDK_DPI_SCALE=0.6
export QT_AUTO_SCREEN_SCALE_FACTOR=1

TRACKBALL="Kensington Slimblade Trackball"

if [ "$(xinput | grep "$TRACKBALL" | wc -l)" -eq "1" ]; then \
    xinput set-prop "$TRACKBALL" "libinput Natural Scrolling Enabled" 1;
    xinput set-prop "$TRACKBALL" "libinput Accel Speed" 1.0;
    # https://gist.github.com/yowcow/c33a00b7ff89e50f6b3a58f24f1072b5
    xinput set-button-map "Kensington Slimblade Trackball" 1 8 3 4 5 9 9 2 9;
fi

TOUCHPAD="SynPS/2 Synaptics TouchPad"

if [ "$(xinput | grep "$TOUCHPAD" | wc -l)" -eq "1" ]; then \
    xinput set-prop "$TOUCHPAD" "libinput Natural Scrolling Enabled" 1;
    xinput set-prop "$TOUCHPAD" "libinput Tapping Enabled" 1;
    xinput set-prop "$TOUCHPAD" "libinput Accel Speed" 1.0;
fi

XRANDR_PRIMARY_OUTPUT="eDP-1"
XRANDR_SCALE="1.0x1.0"
XRANDR_PREV_OUTPUT=$XRANDR_PRIMARY_OUTPUT

xrandr --output $XRANDR_PRIMARY_OUTPUT --mode 2560x1440

for output in $(xrandr -q | awk '$2 == "connected" { print $1 }' | grep -v $XRANDR_PRIMARY_OUTPUT); do
    mode=$(xrandr -q | awk "\$1 == \"$output\" { getline; print \$1; }" | head -n1);
    if [ "$XRANDR_PREV_OUTPUT" = "" ]; then
        xrandr --output $output --mode $mode --scale $XRANDR_SCALE;
    else
        xrandr --output $output --mode $mode --scale $XRANDR_SCALE --left-of $XRANDR_PREV_OUTPUT;
    fi;
    XRANDR_PREV_OUTPUT=$output;
done

for output in $(xrandr -q | awk '$2 == "disconnected" { print $1 }'); do
    xrandr --output $output --off;
done

xmodmap ~/.Xmodmap
xrdb -merge ~/.Xresources

xset r rate 250 60
